import {
  FinancialCalculationResult,
  MaxBidCalculation,
  VehicleDetail,
  VehicleListItem,
  VehicleUpsertRequest,
} from '../core/models/vehicle.models';

const insufficientMaxBid: MaxBidCalculation = {
  status: 'InsufficientData',
  reason: 'A positive sale price is required.',
  salePrice: null,
  minimumProfitAmount: null,
  minimumRoiPercentage: null,
  bidIncrement: 50,
  maxBidByMinimumProfit: null,
  maxBidByMinimumRoi: null,
  mathematicalMaxBid: null,
  finalMaxBid: null,
  bindingConstraint: 'None',
  estimatedCostsAtFinalBid: null,
  totalInvestmentAtFinalBid: null,
  profitAtFinalBid: null,
  roiPercentageAtFinalBid: null,
  marginPercentageAtFinalBid: null,
  minimumProfitSatisfied: null,
  minimumRoiSatisfied: null,
  allConstraintsSatisfied: null,
};

export const emptyFinancialAnalysis: FinancialCalculationResult = {
  reportingCurrency: 'EUR',
  analysisPurchasePrice: null,
  estimatedCostsAtAnalysisPrice: null,
  expectedScenario: {
    salePrice: null,
    totalEstimatedInvestment: null,
    profit: null,
    roiPercentage: null,
    marginPercentage: null,
  },
  conservativeScenario: {
    salePrice: null,
    totalEstimatedInvestment: null,
    profit: null,
    roiPercentage: null,
    marginPercentage: null,
  },
  expectedMaxBid: insufficientMaxBid,
  conservativeMaxBid: insufficientMaxBid,
};

export const vehicleDetail: VehicleDetail = {
  id: 2,
  status: 'Candidate',
  brand: 'Peugeot',
  model: '3008',
  year: 2019,
  vin: null,
  mileage: null,
  engine: null,
  fuelType: null,
  transmissionType: null,
  sourcePlatform: null,
  sourceUrl: null,
  sourceCountry: null,
  physicalLocation: null,
  currentBid: null,
  myBid: null,
  analysisPurchasePrice: null,
  bidIncrement: 50,
  finalPurchasePrice: null,
  purchaseDate: null,
  expectedSalePrice: null,
  conservativeSalePrice: null,
  plannedListingPrice: null,
  minimumAcceptableSalePrice: null,
  actualSalePrice: null,
  listingDate: null,
  saleDate: null,
  minimumProfitAmount: null,
  minimumRoiPercentage: null,
  createdAtUtc: '2026-08-14T10:00:00Z',
  updatedAtUtc: '2026-08-14T10:00:00Z',
  archivedAtUtc: null,
  costEntries: [],
  financialAnalysis: emptyFinancialAnalysis,
};

export const vehicleListItem: VehicleListItem = {
  id: 2,
  status: 'Candidate',
  brand: 'Peugeot',
  model: '3008',
  year: 2019,
  vin: null,
  sourceCountry: 'Италия',
  physicalLocation: 'Милано',
  currentBid: 9500,
  myBid: null,
  analysisPurchasePrice: 10000,
  expectedSalePrice: 16000,
  conservativeSalePrice: 14500,
  archivedAtUtc: null,
  financialSummary: {
    expectedMaxBid: { status: 'Calculated', finalMaxBid: 10600 },
    conservativeMaxBid: { status: 'Calculated', finalMaxBid: 9350 },
    expectedRoiPercentage: 26.3823,
  },
};

export const vehicleRequest: VehicleUpsertRequest = {
  status: 'Candidate',
  brand: 'Peugeot',
  model: '3008',
  year: 2019,
  vin: null,
  mileage: null,
  engine: null,
  fuelType: null,
  transmissionType: null,
  sourcePlatform: null,
  sourceUrl: null,
  sourceCountry: null,
  physicalLocation: null,
  currentBid: null,
  myBid: null,
  analysisPurchasePrice: null,
  bidIncrement: 50,
  expectedSalePrice: null,
  conservativeSalePrice: null,
  plannedListingPrice: null,
  minimumAcceptableSalePrice: null,
  minimumProfitAmount: null,
  minimumRoiPercentage: null,
};
