// <auto-generated />
using System;
using CarDealerManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarDealerManager.Infrastructure.Migrations
{
    [DbContext(typeof(CdmDbContext))]
    partial class CdmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarDealerManager.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_sale_price");

                    b.Property<decimal?>("AnalysisPurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("analysis_purchase_price");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<decimal>("BidIncrement")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("bid_increment");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<decimal?>("ConservativeSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("conservative_sale_price");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("CurrentBid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_bid");

                    b.Property<string>("Engine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine");

                    b.Property<decimal?>("ExpectedSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("expected_sale_price");

                    b.Property<decimal?>("FinalPurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_purchase_price");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fuel_type");

                    b.Property<DateOnly?>("ListingDate")
                        .HasColumnType("date")
                        .HasColumnName("listing_date");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<decimal?>("MinimumAcceptableSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_acceptable_sale_price");

                    b.Property<decimal?>("MinimumProfitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_profit_amount");

                    b.Property<decimal?>("MinimumRoiPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("minimum_roi_percentage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<decimal?>("MyBid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("my_bid");

                    b.Property<string>("PhysicalLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("physical_location");

                    b.Property<decimal?>("PlannedListingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("planned_listing_price");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<DateOnly?>("SaleDate")
                        .HasColumnType("date")
                        .HasColumnName("sale_date");

                    b.Property<string>("SourceCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_country");

                    b.Property<string>("SourcePlatform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_platform");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TransmissionType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("transmission_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_vin")
                        .HasFilter("vin IS NOT NULL");

                    b.HasIndex("ArchivedAtUtc", "Status")
                        .HasDatabaseName("ix_vehicles_archived_status");

                    b.ToTable("vehicles", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_bid_increment", "bid_increment > 0");

                            t.HasCheckConstraint("ck_vehicles_mileage", "mileage IS NULL OR mileage >= 0");

                            t.HasCheckConstraint("ck_vehicles_non_negative_amounts", "(current_bid IS NULL OR current_bid >= 0) AND (my_bid IS NULL OR my_bid >= 0) AND (analysis_purchase_price IS NULL OR analysis_purchase_price >= 0) AND (final_purchase_price IS NULL OR final_purchase_price >= 0) AND (expected_sale_price IS NULL OR expected_sale_price >= 0) AND (conservative_sale_price IS NULL OR conservative_sale_price >= 0) AND (planned_listing_price IS NULL OR planned_listing_price >= 0) AND (minimum_acceptable_sale_price IS NULL OR minimum_acceptable_sale_price >= 0) AND (actual_sale_price IS NULL OR actual_sale_price >= 0) AND (minimum_profit_amount IS NULL OR minimum_profit_amount >= 0) AND (minimum_roi_percentage IS NULL OR minimum_roi_percentage >= 0)");

                            t.HasCheckConstraint("ck_vehicles_year", "year BETWEEN 1886 AND 2200");
                        });
                });

            modelBuilder.Entity("CarDealerManager.Domain.Entities.VehicleCostEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<bool>("IncludedInAnalysis")
                        .HasColumnType("boolean")
                        .HasColumnName("included_in_analysis");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PurchasePricePercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("purchase_price_percentage");

                    b.Property<int?>("RelatedEstimateId")
                        .HasColumnType("integer")
                        .HasColumnName("related_estimate_id");

                    b.Property<decimal?>("RiskPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("risk_percentage");

                    b.Property<decimal?>("TaxPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tax_percentage");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_cost_entries");

                    b.HasIndex("RelatedEstimateId")
                        .HasDatabaseName("ix_vehicle_cost_entries_related_estimate_id");

                    b.HasIndex("VehicleId", "Kind", "ArchivedAtUtc")
                        .HasDatabaseName("ix_vehicle_cost_entries_vehicle_kind_archived");

                    b.ToTable("vehicle_cost_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_cost_entries_kind_shape", "(kind = 'Estimated' AND related_estimate_id IS NULL AND (amount > 0 OR purchase_price_percentage > 0)) OR (kind = 'Actual' AND amount > 0 AND purchase_price_percentage IS NULL AND tax_percentage IS NULL AND risk_percentage IS NULL)");

                            t.HasCheckConstraint("ck_vehicle_cost_entries_non_negative", "amount >= 0 AND (purchase_price_percentage IS NULL OR purchase_price_percentage >= 0) AND (tax_percentage IS NULL OR tax_percentage >= 0) AND (risk_percentage IS NULL OR risk_percentage >= 0)");
                        });
                });

            modelBuilder.Entity("CarDealerManager.Domain.Entities.VehicleCostEntry", b =>
                {
                    b.HasOne("CarDealerManager.Domain.Entities.VehicleCostEntry", "RelatedEstimate")
                        .WithMany("RelatedActualCosts")
                        .HasForeignKey("RelatedEstimateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vehicle_cost_entries_related_estimate_id");

                    b.HasOne("CarDealerManager.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("CostEntries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_cost_entries_vehicles_vehicle_id");

                    b.Navigation("RelatedEstimate");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarDealerManager.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("CostEntries");
                });

            modelBuilder.Entity("CarDealerManager.Domain.Entities.VehicleCostEntry", b =>
                {
                    b.Navigation("RelatedActualCosts");
                });
#pragma warning restore 612, 618
        }
    }
}
